sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk9

branches:
  only:
  - master
  - develop
  - release-*

before_install:
 - mvn clean

after_success:
  - mvn clean cobertura:cobertura coveralls:report -P coveralls.io

