sudo: false
language: java

cache:
  directories:
    - "$HOME/.m2"

before_cache:
  - rm -rf $HOME/.m2/repository/com/github/mpkorstanje/simmetrics

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - develop
  - release-*

before_install:
  - mvn clean

after_success:
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
